### ISSUE TITLE
为什么我在cmd中执行npm install后就卡在loadRequestDeps了？

### ISSUE THREAD

**Issue by xyxc0673** [chemzqm/wept#1]
nodejs-v6.8
win10 64

**Comment by xyxc0673** [comment]
好吧，现在好了

**Comment by johnwang77** [comment]
D:\JWKit>wept
F:\software\work\nodejs\node_global\node_modules\wept\lib\server.js:15
let socket
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (F:\software\work\nodejs\node_global\node_modules\wept\bin\wept:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

在小程序目录执行 wept，出现上述错误，请教~~

**Comment by chemzqm** [comment]
应该是网络问题
