### ISSUE TITLE
发生了未知错误

### ISSUE THREAD

**Issue by zhyc9de** [chemzqm/wept#109]
* `wept --version`: 0.9.1 140900
* `node --version`: v8.4.0
* 操作系统: osx 10.12.6
* 浏览器及浏览器版本: 60.0.3112.113
## 错误日志

发生了未知错误
Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at exports.execFile (child_process.js:208:15)
    at /usr/local/lib/node_modules/wept/build/parser.js:76:9
    at /usr/local/lib/node_modules/wept/build/parser.js:42:12
    at Parallel.cb (/usr/local/lib/node_modules/wept/node_modules/node-parallel/index.js:65:8)
    at Parallel.done (/usr/local/lib/node_modules/wept/node_modules/node-parallel/index.js:68:42)
    at /usr/local/lib/node_modules/wept/build/util.js:161:7
    at tryToString (fs.js:513:3)

**Comment by chemzqm** [comment]
文件没有可执行权限
```
chmod +x /usr/local/lib/node_modules/wept/bin/wcc
chmod +x /usr/local/lib/node_modules/wept/bin/wcsc
```
