### ISSUE TITLE
无法正常监听，有报错

### ISSUE THREAD

**Issue by goldcome** [chemzqm/wept#111]
* `wept --version`: 0.9.2 140900
* `node --version`: v6.11.2
* 操作系统: Ubuntu Server 14.04 
* 浏览器及浏览器版本: Firefox 55.0.3
* 与官方工具表现不一致？

## 错误日志
```
listening on port 8003
 ✓ service.js build success
An error occured. { Error: spawn notify-send ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn notify-send',
  path: 'notify-send',
  spawnargs: 
   [ '-i',
     'Safari',
     '--hint=int:transient:1',
     'liveload',
     '',
     'Reloading pages/index/index.wxml' ] }
 ✓ pages/index/index.wxml rebuild success
```

**Comment by chemzqm** [comment]
```
sudo apt-add-repository ppa:izx/askubuntu
sudo apt-get update
sudo apt-get install libnotify-bin
```
或许可以解决，你可以试下这个包：`https://www.npmjs.com/package/chokidar`
是不是可以正常使用，怀疑是缺少 notify 所需依赖导致报错。
