### ISSUE TITLE
不支持ES6?

### ISSUE THREAD

**Issue by DreamboyA** [chemzqm/wept#122]
* `wept --0.9.2 140900`: 
* `node --v8.9.4`: 
* 操作系统: Mac 10.13.1
* 浏览器及浏览器版本:  Chrome 63.0.3239.132
* 与官方工具表现不一致？ 否

执行wept报错

## 错误日志

<pre>
<code>

listening on port 3000
utils/context.js: Unexpected token (6:25)
SyntaxError: utils/context.js: Unexpected token (6:25)
  4 | class context{
  5 |
> 6 |   static play_audio_data = {};
    |                          ^
  7 |   static call_stop_play = false;
  8 |
  9 |   static play_audio(this_object, path){
    at Parser.pp$5.raise (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$1.parseClassProperty (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:2571:50)
    at Parser.pp$1.parseClassBody (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:2516:34)
    at Parser.pp$1.parseClass (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:2406:8)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:1843:19)
    at Parser.pp$1.parseBlockBody (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:1673:17)
    at parse (/usr/local/lib/node_modules/wept/node_modules/babylon/lib/index.js:7305:37)

</code>
</pre>

**Comment by chemzqm** [comment]
你这个不是es6语法，属于 stage 阶段或者 es7
