### ISSUE TITLE
wept不能正常监听代码变化？

### ISSUE THREAD

**Issue by fh-combo** [chemzqm/wept#126]
* `wept --version`: 0.9.6 140900
* `node --version`: v8.9.3
* 操作系统: windows 7
* 浏览器及浏览器版本: chrome  69.0.3452.0 正式版
* 与官方工具表现不一致？

## 错误日志
$ wept
listening on port 3000
 ✓ service.js build success
An error occured. { Error: spawn growlnotify ENOENT
    at _errnoException (util.js:1024:11)    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn growlnotify',
  path: 'growlnotify',
  spawnargs:
   [ '/i:Safari',
     'Reloading pages/index/index.wxml',     '/t:liveload' ] }ml
     'Reloading pages/index/index.wxml',     '/t:liveload' ] } ✓ pages/index/index.wxml rebuild success

**Comment by chemzqm** [comment]
这个模块已经不维护了，官方的 ide 已经很好用了
