### ISSUE TITLE
不支持es6，跑不起来

### ISSUE THREAD

**Issue by xiao345** [chemzqm/wept#17]
* `wept --version`: 
* `node --version`: 
* 操作系统: 
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志
➜  wept git:(master) ✗ wept -V
/usr/local/lib/node_modules/wept/lib/server.js:15
let socket
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/wept/bin/wept:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by chemzqm** [comment]
@xiao345 `lib` 下的代码在 0.3 之前应该是都编译成 es5 的，你这是从我源码你跑的结果吗？
建议安装使用 npm 安装： 

    npm install wept@latest -g

**Comment by xiao345** [comment]
我下的是之前的，现在可以了
