### ISSUE TITLE
Error: Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by huntbao** [chemzqm/wept#37]
* `wept --version`: 0.3.5 101400
* `node --version`: v4.4.5
* 操作系统: OS X El Capitan 10.11.5
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志
Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/wept/build/server.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by chemzqm** [comment]
诡异的 npm 问题，我用的 npm 是可以找到的，已在 0.3.6 修复。
感谢反馈。
