### ISSUE TITLE
今天更新后 WXSS 无法编译

### ISSUE THREAD

**Issue by yangg** [chemzqm/wept#44]
```
Error: Command failed: /Users/brook/.nvm/versions/node/v6.2.1/lib/node_modules/wept/bin/wcsc -lc ./app.wxss
ERR: path `components/bottomnav/bottomnav.wxss` not found from `./app.wxss`.
```
今天更新后，wxss 里只要有 import 的路径全不对了

**Comment by yangg** [comment]
另外，既然代理增加了配置文件，那默认端口也可以到配置文件里配置才好，因为hexo server好像默认用了3000端口（好像是browsersync用的），所以感觉默认3000端口不是个好默认值，或者说可以设置成默认某一个值，然后检查是否可用，不可用就加1，这样想用wept打开多个小程序时比较有用，不用传参数，反正启动后会告诉是哪个端口。

**Comment by chemzqm** [comment]
0.4.1 中修复了 wxss 中无法使用 @import 的问题，你可能用的是 0.4.0
端口可以通过命令行 -p 参数修改，我可以改成同时支持配置文件里面的 port

**Comment by yangg** [comment]
好的，多谢改端口我知道，只是觉得可以方便点

Get Outlook for iOS




On Sun, Nov 13, 2016 at 3:18 PM +0800, "Qiming zhao" <notifications@github.com> wrote:












0.4.1 中修复了 wxss 中无法使用 @import 的问题，你可能用的是 0.4.0

端口可以通过命令行 -p 参数修改，我可以改成同时支持配置文件里面的 port

**Comment by yangg** [comment]
This error still occurs  in
```
wept --version
0.4.2 103100
```

**Comment by chemzqm** [comment]
把你的 app.wxss 文件和目录文件结构发出来我看下。

**Comment by yangg** [comment]
@import "components/bottomnav/bottomnav.wxss";

components 目录在项目根目录下。

**Comment by chemzqm** [comment]
@yangg 找到问题了，我把非 `.` 开头的 import 当作相对当前页面路径处理了，我会尽快修复的。

**Comment by chemzqm** [comment]
微信方面设计 API 设计坑人，他们的 wxml 相对的是文件，而 wxss 相对的是项目根路径。

**Comment by chemzqm** [comment]
@yangg 我测试了 0.4.2 版本是没问题的，你把错误日志再发一下，看下是不是找不到 import 对应文件

**Comment by yangg** [comment]
是同一级啊，微信开发工具没问题。
```
Error: Command failed: /Users/brook/.nvm/versions/node/v6.2.1/lib/node_modules/wept/bin/wcsc -lc ./app.wxss
ERR: path `components/bottomnav/bottomnav.wxss` not found from `./app.wxss`.

error file count: 0

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
Error: app.wxss 编译失败，请检查
    at /Users/brook/.nvm/versions/node/v6.2.1/lib/node_modules/wept/build/parser.js:60:27
    at ChildProcess.exithandler (child_process.js:214:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  --> GET /app/app.wxss?w=375&r=2 404 89ms -
Error: Command failed: /Users/brook/.nvm/versions/node/v6.2.1/lib/node_modules/wept/bin/wcsc -lc ./pages/index/index.wxss ./components/goods/goods.wxss
ERR: path `../../components/loadmore/loadmore.wxss` not found from `./pages/index/index.wxss`.
path `../../components/backtop/backtop.wxss` not found from `./pages/index/index.wxss`.

error file count: 0

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
Error: pages/index/index.wxss 编译失败，请检查
    at /Users/brook/.nvm/versions/node/v6.2.1/lib/node_modules/wept/build/parser.js:60:27
    at ChildProcess.exithandler (child_process.js:214:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by jackyon** [comment]
我也是同样的情况：

ERR: path `style/font.wxss` not found from `./app.wxss`.
path `style/white-block.wxss` not found from `./app.wxss`.
path `style/car-config.wxss` not found from `./app.wxss`.
path `style/weui.wxss` not found from `./app.wxss`.
path `style/tag.wxss` not found from `./app.wxss`.
path `style/animate.wxss` not found from `./app.wxss`.
path `style/tab-animate.wxss` not found from `./app.wxss`.
path `tmpl/swiper/swiper.wxss` not found from `./app.wxss`.
path `tmpl/loader/loader.wxss` not found from `./app.wxss`.
path `tmpl/appslide/appslide.wxss` not found from `./app.wxss`.
path `tmpl/listView/listView.wxss` not found from `./app.wxss`.
path `tmpl/tab/tab.wxss` not found from `./app.wxss`.
path `tmpl/not-found/not-found.wxss` not found from `./app.wxss`.
path `tmpl/result/result.wxss` not found from `./app.wxss`.

**Comment by chemzqm** [comment]
@yangg @jackyon 你们的 app.wxss 中 @import 是怎么写的？

**Comment by jackyon** [comment]
@chemzqm 

```
@import 'style/styles.wxss';
@import 'style/font.wxss';
@import 'style/white-block.wxss';
@import 'style/car-config.wxss';
@import 'style/weui.wxss';
@import 'style/tag.wxss';
@import 'style/animate.wxss';
@import 'style/tab-animate.wxss';

/*模板样式*/
@import 'tmpl/swiper/swiper.wxss';
@import 'tmpl/loader/loader.wxss';
@import 'tmpl/appslide/appslide.wxss';
@import 'tmpl/listView/listView.wxss';
@import 'tmpl/tab/tab.wxss';
@import 'tmpl/not-found/not-found.wxss';
@import 'tmpl/result/result.wxss';
```

**Comment by chemzqm** [comment]
确实有 bug，是我哪里写错了

**Comment by chemzqm** [comment]
@yangg 你的跟他的不一样，因为你一个 import 文件都没找到，我怀疑是没写分号导致的。
@jackyon 你的问题应该已经修复了

**Comment by jackyon** [comment]
貌似npm包还没更新到，现在还是0.4.3版本

**Comment by chemzqm** [comment]
@jackyon 刚发
<img width="325" alt="screen shot 2016-11-14 at 4 38 01 pm" src="https://cloud.githubusercontent.com/assets/251450/20258074/bbe660d2-aa88-11e6-93ca-3aa736fd742e.png">

**Comment by jackyon** [comment]
problem solved, thx!
