### ISSUE TITLE
Windows10 环境下，运行成功一次，使用一段时间后重启报错：Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by zhan3333** [chemzqm/wept#46]
* `wept --version`: 0.5.2 103100
* `node --version`: v6.2.2
* 操作系统: windows10
* 浏览器及浏览器版本: 54.0.2840.99 m (64-bit)
* 与官方工具表现不一致？是

## 错误日志
$ wept
listening on port 3000
undefined
undefined
E:\123\nodejs\global\node_modules\wept\node_modules\.1.9.2@growl\lib\growl.js:27                                                                                                       2
      args.push(quote(msg).replace(/\\n/g, '\n'));
                          ^

TypeError: Cannot read property 'replace' of undefined
    at growl (E:\123\nodejs\global\node_modules\wept\node_modules\.1.9.2@growl\l                                                                                                       ib\growl.js:272:27)
    at Object.exports.notifyError (E:\123\nodejs\global\node_modules\wept\build\                                                                                                       util.js:208:3)
    at onError (E:\123\nodejs\global\node_modules\wept\build\init.js:44:8)
    at E:\123\nodejs\global\node_modules\wept\build\init.js:31:42
    at FSReqWrap.oncomplete (fs.js:117:15)

## 界面截图（可选）
![image](https://cloud.githubusercontent.com/assets/15830778/20463583/8c79dea8-af71-11e6-818a-0bc5d8f66612.png)

**Comment by chemzqm** [comment]
有行代码写错了

**Comment by chemzqm** [comment]
@zhan3333 应该是你在 app.json 里面配置了一个路由，但是 wept 找不到对应 wxml 文件所以导致报错。

**Comment by zhan3333** [comment]
@chemzqm 应该是这个问题，我在app.json中配置了路由但对应文件还没有建立完，晚上回去查看后给你答复；

**Comment by zhan3333** [comment]
@chemzqm 确实是是这样的，新建完所有文件后，可以正常运行。非常感谢
