### ISSUE TITLE
wept 指令报错

### ISSUE THREAD

**Issue by AngryBaby** [chemzqm/wept#7]
* `node --version`: v3.0.0
* 操作系统: OS X 10.12
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志
xxx.nvm/versions/node/v5.0.0/lib/node_modules/wept/bin/wept:18
  exec(`osascript chrome.scpt ${port}`, {cwd: __dirname}, () => {
                                                           ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:952:3

**Comment by chemzqm** [comment]
@AngryBaby node 版本有点低，不支持 es6 的 string template 语法，后续会改进支持更低版本 node

**Comment by AngryBaby** [comment]
@chemzqm 支持node5.0.0 吗？

**Comment by AngryBaby** [comment]
@chemzqm 看到了 我先升级到>6.0吧，不过至少支持到node5.0.0吧

**Comment by chemzqm** [comment]
@AngryBaby 我加个 babel 转一下好了。

**Comment by chemzqm** [comment]
@AngryBaby 0.2.5 加入了 babel 对服务端代码转换，理论上可以支持 node > 1.0
