### ISSUE TITLE
运行wept出错，报Not Found

### ISSUE THREAD

**Issue by weilannet** [chemzqm/wept#85]
* `wept --version`: 
0。9。0
* `node --version`: 
5。7。0
* 操作系统: 
WINDOWS
* 浏览器及浏览器版本: 
CHROM
* 与官方工具表现不一致？
在小程序目录直接运行wept，访问路径localhost:3000/pages/index 报错

## 错误日志
BadRequestError: Malicious Path
    at resolvePath (C:\dev\nvm\v5.7.0\node_modules\wept\node_modules\resolve-path\index.js:77:11)
    at C:\dev\nvm\v5.7.0\node_modules\wept\node_modules\koa-send\index.js:69:12
    at next (native)
    at onFulfilled (C:\dev\nvm\v5.7.0\node_modules\wept\node_modules\co\index.js:65:19)
    at C:\dev\nvm\v5.7.0\node_modules\wept\node_modules\co\index.js:54:5
    at co (C:\dev\nvm\v5.7.0\node_modules\wept\node_modules\co\index.js:50:10)
    at send (C:\dev\nvm\v5.7.0\node_modules\wept\node_modules\koa-send\index.js:36:10)
    at Object.serve (C:\dev\nvm\v5.7.0\node_modules\wept\node_modules\koa-static\index.js:41:19)
    at next (native)
    at Object.allowedMethods (C:\dev\nvm\v5.7.0\node_modules\wept\node_modules\koa-router\lib\router.js:374:5)

**Comment by chemzqm** [comment]
@weilannet 貌似是 node  5.7.0 的 bug https://github.com/koajs/send/issues/51
请尝试升级 node 版本，另 localhost:3000/pages/index 这个路径是不存在的，请访问 localhost:3000
